openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8081
  description: Generated server url
paths:
  /api/v1/documents:
    get:
      tags:
      - doc-controller
      operationId: listAllDocuments
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DocDto"
    post:
      tags:
      - doc-controller
      operationId: addDocument
      requestBody:
        content:
          application/json:
            schema:
              required:
              - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DocDto"
  /api/v1/documents/{id}:
    get:
      tags:
      - doc-controller
      operationId: getDocument
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DocDto"
    delete:
      tags:
      - doc-controller
      operationId: deleteDocument
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
    patch:
      tags:
      - doc-controller
      operationId: updateDocument
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateDocRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DocDto"
  /api/v1/documents/search/{searchText}:
    get:
      tags:
      - doc-controller
      operationId: searchDocuments
      parameters:
      - name: searchText
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DocDto"
components:
  schemas:
    DocDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        originalFilename:
          type: string
        contentType:
          type: string
        size:
          type: integer
          format: int64
        uploadDate:
          type: string
          format: date-time
    UpdateDocRequest:
      required:
      - originalFilename
      type: object
      properties:
        originalFilename:
          type: string
