openapi: "3.1.0"
info:
  title: "paperless_rest API"
  description: "paperless_rest API"
  version: "1.0.0"
servers:
  - url: "https://paperless_rest"
paths:
  /api/v1/documents:
    post:
      summary: "POST api/v1/documents"
      operationId: "addDocument"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              required:
                - "file"
              properties:
                file:
                  type: "string"
                  format: "binary"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DocDto"
    get:
      summary: "GET api/v1/documents"
      operationId: "listAllDocuments"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/DocDto"
  /api/v1/documents/{id}:
    get:
      summary: "GET api/v1/documents/{id}"
      operationId: "getDocument"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DocDto"
    patch:
      summary: "PATCH api/v1/documents/{id}"
      operationId: "updateDocument"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateDocRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DocDto"
    delete:
      summary: "DELETE api/v1/documents/{id}"
      operationId: "deleteDocument"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Void"
  /api/v1/documents/search/{searchText}:
    get:
      summary: "GET api/v1/documents/search/{searchText}"
      operationId: "searchDocuments"
      parameters:
        - name: "searchText"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/DocDto"
components:
  schemas:
    Date:
      type: "object"
      properties: { }
    DocDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        originalFilename:
          type: "string"
        contentType:
          type: "string"
        size:
          type: "integer"
          format: "int64"
        uploadDate:
          $ref: "#/components/schemas/Date"
    UpdateDocRequest:
      type: "object"
      properties:
        originalFilename:
          type: "string"
    Void:
      type: "object"
      properties: { }